FROM randomdeude/gcc-cross-x75_g4-elf

RUN apt-get update
RUN apt-get upgrade -y nasm
RUN apt-get install -y xorriso
RUN apt-get install -y grub-pc-bin
RUN Apt-get install -y grub-common

VOLUME /root/env
WORKDIR /root/env